### ISSUE TITLE
Errors with configuration files after running pgmodeler

### ISSUE THREAD

**Issue by lourdas** [linux0uid/gentoo-overlay#1]
After successfully compiling pgmodeler with the ebuild provided here, when I run the binary, I get this error:

```
Failed to create initial configuration in /home/xxx/.config/pgmodeler! Check if the current user has write permission over that path and at least read permission over /var/tmp/portage/dev-db/pgmodeler-0.8.0/work/pgmodeler-0.8.0/conf.
```

So, I tried to do some fiddling with the source. I unpacked the ebuild, and copied the conf directory (all files inside I mean) under .config/pgmodeler. I tried to run the binary again and I get:

```
Unable to load one or more configuration files! Please check if files exists in the configuration folder and if they are not corrupted to preventing this error to occur again on the next startup!
```

However, this time the application opened. I still got an error. Running the binary from terminal, I get:

```
I/O error : failed to load external entity "/var/tmp/portage/dev-db/pgmodeler-0.8.0/work/pgmodeler-0.8.0/schemas/xml/dtd/dbmodel.dtd"
portage/dev-db/pgmodeler-0.8.0/work/pgmodeler-0.8.0/schemas/xml/dtd/dbmodel.dtd"
                                                                           ^
validity error : Validation failed: no DTD found !
```

I suppose that fixing these small issues will make the ebuild great. Thanks!!!

**Comment by linux0uid** [comment]
For now You can use start-pgmodeler.sh for start pgmodeler
I will change this (rename start-pgmodeler.sh to pgmodeler) after a while.

**Comment by linux0uid** [comment]
I changed it. Can you check?
Now you can call pgmodeler or /usr/bin/pgmodeler.
P.S. If you use layman, you must do something like this:
sudo layman -S

**Comment by linux0uid** [comment]
@lourdas You may try a new versions of pgmodeler.
If you have not this issue anymore, you may to close it.

**Comment by lourdas** [comment]
@linux0uid Yes, it seems to work just fine now. Emerged 0.8.2-beta and so far it hasn't crashed or throw any exception. Good work!
